name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
      - stage
  workflow_dispatch:

jobs:
  build:
    uses: simonheimlicher/claris-gh-actions/.github/workflows/jobs/build-hugo.yml@main
    with:
      hugo_version: '0.121.2'
    secrets:
      HUGO_CLARIS_AUTHOR_EMAIL: ${{ secrets.HUGO_CLARIS_AUTHOR_EMAIL }}

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stage'
    uses: simonheimlicher/claris-gh-actions/.github/workflows/jobs/deploy-cloudflare-pages.yml@main
    with:
      branch_name: ${{ github.ref_name }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ github.ref == 'refs/heads/main' && secrets.CLOUDFLARE_ACCOUNT_ID || secrets.CLOUDFLARE_STAGE_ACCOUNT_ID }}
      CLOUDFLARE_PROJECT_NAME: ${{ github.ref == 'refs/heads/main' && secrets.CLOUDFLARE_PROJECT_NAME || secrets.CLOUDFLARE_STAGE_PROJECT_NAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}